WIP - /resources redesign
canonical/microk8s.io pull request #607
Opened 2023-08-14 16:12 UTC by mtruj013

## Done

- Applired redesign as per [doc](https://docs.google.com/document/d/1PB5-CamGmSjhbuyuGSariC9zUW-8krAJD0l8JyvNk20/edit) and [design](https://www.figma.com/file/0DTIS3uNNUuDAdCKWrk8Uf/23.10---Microk8s.io?type=design&node-id=0-1&mode=design&t=IiSkurvj9PifdsoF-0)
- Added Canonical image template

## QA

- View the site locally in your web browser at: http://0.0.0.0:8027/resources
- Check page against doc and design 

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-4192

2023-08-18 08:08 UTC, anthonydillon requested changes
Looking good @mtruj013 some small suggestions in the code

2023-08-18 08:08 UTC, anthonydillon commented on static/sass/_pattern_resources.scss
> +    color: white;
Can you add `color` to the `.p-card--resources` element. If you set the background we should set color and we are not guaranteed to have h2 is all use cases.

2023-08-18 08:08 UTC, anthonydillon commented on templates/resources/videos-and-webinars.html
> +      <a href="https://www.youtube.com/watch?v=v9KI2BAF5QU"><i class="p-icon--video-play is-light"></i></a>
```suggestion
      <a href="https://www.youtube.com/watch?v=v9KI2BAF5QU"><i class="p-icon--video-play is-light">Watch the What is MicroK8s? video</i></a>
```

Empty links are no accessible. Icon patterns already hide the content allowing linking to contain contextual text.

2023-08-18 08:08 UTC, anthonydillon commented on templates/resources/videos-and-webinars.html
> +      <a href="https://www.youtube.com/watch?v=v9KI2BAF5QU"><i class="p-icon--video-play is-light"></i></a>
Same for all the media links in this doc

2023-08-18 14:35 UTC, mtruj013 commented
Thanks @anthonydillon, could you take another look?

2023-08-18 14:44 UTC, juanruitina commented
Please make the titles for all videos, publications and posts `h3` to keep a clean heading tree (formatting is OK). Other than that, LGTM.

2023-08-18 15:51 UTC, anthonydillon approved these changes
Perfect, thanks :+1:

2023-08-21 15:56 UTC, mtruj013 commented
@lyubomir-popov I made the changes, but I'm not sure I understood the spacing for the video and webinars section, so a few questions here if you don't mind

> shallow sections wrapping these images (one has shallow spacing, the other none):

Do you mean that shallow sections should wrap all but the last one? Or that the first one is supposed to be wrapped in a shallow section, but the rest are not? Also, in changing the wrapping divs for these to shallow sections instead shallow strips we lose the spacing between the hr and the card.
![image](https://github.com/canonical/microk8s.io/assets/17607612/f66f7e34-9f43-41ab-9b82-e743360723f3)

What is the spacing supposed to be for the separators? IIRC we're not supposed to be using utility classes and it's not specified in dev mode on the figma file. 

Lastly, [as Juan pointed out ](https://github.com/canonical/microk8s.io/pull/607#issuecomment-1684027009), the thumbnail overlaps with the text on small screens, what is the card supposed to look like in these situations?

Please let me know if the other changes I pushed are correct. Thanks!

2023-08-21 16:08 UTC, lyubomir-popov commented
> And some visual feedback: the video thumbnail doesn't seem to downscale well on mobile, @lyubomir-popov any thoughts?

How about this design @juanruitina @mtruj013? I would make the whole card clickable. a Subtle affordance could be a gentle zoom on the background, as Ant did on the RFQ cards

<img width="615" alt="image" src="https://github.com/canonical/microk8s.io/assets/2741678/49ce634a-ff0e-4ef7-9cf9-2691a11010a9">

2023-08-21 16:19 UTC, lyubomir-popov commented
@mtruj013 sorry forgot to mention, everythign else looks great. One question about the sidenav - shouldn't it respod toscrolling and highlight the current section? ATM, if I click the last entry in it and relaod, it still stays highlighted, even though I'm at the top of the page - where the first sidenav item should be highlighted:
<img width="1145" alt="image" src="https://github.com/canonical/microk8s.io/assets/2741678/b544df42-85d2-4124-9ab3-2d80f5998b7c">

2023-08-22 09:17 UTC, mtruj013 commented
@lyubomir-popov I quite like that card design! I'll make the update and fix active tab change on scroll as well

2023-08-22 12:02 UTC, mtruj013 commented
@lyubomir-popov  Addressed everything with the exception of setting active tabs based on what's in the viewport. For context, this is a new use case for this component (that functionality doesn't exist on u.com or c.com). I had a go, but I'm still getting bugs and I don't have much more time to keep playing around with it. If you can think of an example where this is already live and implemented please link so I can take a look and replicate, but otherwise I think it might be better to make a follow up ticket

2023-08-22 12:02 UTC, lyubomir-popov commented
Hi @mtruj013 sorry to keep pestering you, but there are still a few things to polish here:

- the second section should be a p-section--deep, not p-strip - a p-strip doubles the space between hero and the next thing. And also, since this section wraps all subsequent content, it should be deep - so once the dark footer comes in, there's a deep space (8rem) between the last item on paper background, and the dark, contrasting footer.
<img width="1540" alt="image" src="https://github.com/canonical/microk8s.io/assets/2741678/953e384f-daf9-42a4-b9e9-8c981c36d0ab">

- the text zooms with the background - and it needs easing. ease-out, there's a preset in vanilla.

- the text here:
<img width="523" alt="image" src="https://github.com/canonical/microk8s.io/assets/2741678/6c267781-3b34-4fa7-82eb-f256caeb1c42">
is still at a different distance from all others:
<img width="263" alt="image" src="https://github.com/canonical/microk8s.io/assets/2741678/f23c4f2e-f004-43e9-b1ab-46d63fee40c2">


- this `hr` needs a `p-rule` class. Only `hr`s above images, buttons and other block elements should have no class. This is because they would otherwise stick to the element following them. All `hr`s that have a piece of text after them should have the `p-rule` class, as all text already has a padding top.

2023-08-22 12:04 UTC, lyubomir-popov commented
> Addressed everything with the exception of setting active tabs based on what's in the viewport. For context, this is a new use case for this component (that functionality doesn't exist on u.com or c.com). I had a go, but I'm still getting bugs and I don't have much more time to keep playing around with it. If you can think of an example where this is already live and implemented please link so I can take a look and replicate, but otherwise I think it might be better to make a follow up ticket

@mtruj013 cc-ing @bartaz here who might know. I think we can launch like this and have a separate known issue to fix it later. Please see the comments above for a few small remaining glitches. Once those are addressed, this is good to go.

2023-08-23 12:58 UTC, lyubomir-popov commented
video and text still diff widfths:
<img width="782" alt="image" src="https://github.com/canonical/microk8s.io/assets/2741678/d8083baf-31a9-4739-84f5-7e24da8e7dbb">

2023-08-23 13:06 UTC, mtruj013 commented on static/sass/_pattern_resources.scss
> +  width:  35rem;
I don't understand this question, no idea what "1005 of the middle 6 columns" means

2023-08-23 13:11 UTC, lyubomir-popov commented
@mtruj013 sorry meant 100% of the parent container, which should be a col-6

2023-08-24 11:11 UTC, lyubomir-popov commented
looks great thanks @mtruj013 !

2023-08-24 11:18 UTC, merged