Apply /contact-us redesign
canonical/microk8s.io pull request #611
Opened 2023-08-18 07:27 UTC by mtruj013

## Done

- Applied redesign as per [doc](https://docs.google.com/document/d/1KkLHMrGipY4zgIXreujpyJlLvYUs-iAlP-FtpYrZmWA/edit) and [design](https://www.figma.com/file/0DTIS3uNNUuDAdCKWrk8Uf/23.10---Microk8s.io?node-id=407%3A6063&mode=dev)

## QA

- View the site locally in your web browser at: http://0.0.0.0:8027/contact-us
- Check against doc and design

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-4196

2023-08-18 07:27 UTC, webteam-app commented
Demo starting at https://microk8s-io-611.demos.haus

2023-08-18 07:53 UTC, lyubomir-popov commented
looks great, thanks @mtruj013

2023-08-18 08:13 UTC, anthonydillon requested changes
The form in Marketo does not match the form here: 
![image](https://github.com/canonical/microk8s.io/assets/1413534/c827ffb4-08c2-4902-9cdb-e9b1af59a6dd)

2023-08-18 08:17 UTC, anthonydillon requested changes

2023-08-18 08:17 UTC, anthonydillon commented on static/sass/styles.scss
> +}
Personally, I would add `u-no-padding--bottom` to the li's instead of a new class.

2023-08-18 14:42 UTC, juanruitina commented
* On mobile, the consent checkbox and the label are not aligned.
* Can you please add a bit of space between that and the "By submitting this form..." line, to make clear they are not related?

<img width="334" alt="Screenshot 2023-08-18 at 16 38 37" src="https://github.com/canonical/microk8s.io/assets/1409729/9cdf1d29-c7e3-46b8-8fef-4781daba94dd">

LGTM otherwise!

2023-08-23 06:13 UTC, mtruj013 commented
Thanks all! @juanruitina and @anthonydillon could you take another look? Sophie solved the marketo fields issue, we're using a new form so the id has been updated

2023-08-23 10:00 UTC, anthonydillon requested changes
The form looks good but First name, Last name, Email and Phone number are required fields in Marketo.

Could you use the [Vanilla pattern for required fields](https://vanillaframework.io/docs/base/forms#required)?

2023-08-23 10:48 UTC, mtruj013 commented
Thanks @anthonydillon, could you take another look? I updated the required fields to use the Vanilla pattern, but omitted the legend as this is already accounted for in the copy (`"* Mandatory field"` further down in the page)

2023-08-23 11:29 UTC, anthonydillon approved these changes
Nice, thanks @mtruj013

2023-08-23 16:04 UTC, juanruitina commented
LGTM!

2023-08-23 19:48 UTC, merged