Apply redesign to nav and footer
canonical/microk8s.io pull request #614
Opened 2023-08-23 07:51 UTC by mtruj013

## Done

- Update to latest global nav version
- Apply redesign to nav and footer as per Jira ticket 

## QA

- View the site locally in your web browser at: http://0.0.0.0:8027/
- Check nav and footer against design
- Make sure all links work as expected **(/features will 404, this will be fixed once https://github.com/canonical/microk8s.io/pull/613 is merged)**

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-5794

2023-08-23 09:03 UTC, anthonydillon requested changes
LGTM one small comment about the `is-selected` as this makes it difficult to know where you are.

2023-08-23 09:03 UTC, anthonydillon commented on templates/partial/_navigation.html
> +        <li class="p-navigation__item">
Looks like these links are missing the `is-selected` if the `request.path` matches.

2023-08-23 11:16 UTC, mtruj013 commented
Thanks @anthonydillon, fixed! Could you take a look again?

2023-08-23 11:27 UTC, anthonydillon commented
Thanks for the fixes @mtruj013 Looks and works great!

2023-08-23 11:27 UTC, anthonydillon approved these changes

2023-08-23 11:32 UTC, lyubomir-popov commented
u-no-margin--bottom here please:
<img width="1506" alt="image" src="https://github.com/canonical/microk8s.io/assets/2741678/67877d91-db12-42ee-b567-5526c8efdaaf">
(driveby)


logo too indented here:
<img width="845" alt="image" src="https://github.com/canonical/microk8s.io/assets/2741678/c6212dab-f006-4295-bb7b-23abb0230be0">


menu items should align under the wordmark microk8s (coukld be a vanilla bug)


would be nice to retain some layout on medium screens, e.g.:
<img width="849" alt="image" src="https://github.com/canonical/microk8s.io/assets/2741678/8bbe7ed4-664b-4ef1-90fa-1a4ce3819252">

2023-08-23 13:51 UTC, mtruj013 commented
@lyubomir-popov ready for another look

2023-08-23 14:09 UTC, lyubomir-popov commented
LGTM, thanks @mtruj013 . can I as kfor a driveby - add u-no-margin-bottom on the landing page h1

2023-08-23 15:15 UTC, mtruj013 commented
@lyubomir-popov sorry, totally thought I'd added it. It's there now

2023-08-23 16:11 UTC, juanruitina commented
Lovely to see the new navigation and footer. We need however to implement the [sliding navigation](https://vanillaframework.io/docs/patterns/navigation#sliding) here so the global nav shows up as it should on mobile: as only one item you can then open. You can see what I mean [here on Figma](https://www.figma.com/file/BSP7FqnRMcMvO7kCozJKUa/Ubuntu.com-navigation-update-Iteration-9?type=design&node-id=1323%3A3714&mode=design&t=8EWcyAlY63UIVgJz-1). @petesfrench might be able to help with the implementation, he is familiar with it.

2023-08-23 17:58 UTC, petesfrench commented
> Lovely to see the new navigation and footer. We need however to implement the [sliding navigation](https://vanillaframework.io/docs/patterns/navigation#sliding) here so the global nav shows up as it should on mobile: as only one item you can then open. You can see what I mean [here on Figma](https://www.figma.com/file/BSP7FqnRMcMvO7kCozJKUa/Ubuntu.com-navigation-update-Iteration-9?type=design&node-id=1323%3A3714&mode=design&t=8EWcyAlY63UIVgJz-1). @petesfrench might be able to help with the implementation, he is familiar with it.

Happy to help with this, but the best course of action would be to implement it on the global-nav itself. This needs to be done at one point and will mean it is available across all projects.

2023-08-24 09:07 UTC, mtruj013 commented
re: sliding navigation in the global nav. It was decided during stand-up the this will be updated directly on the global-nav, we will go live with this site as is

@juanruitina would you mind giving UX+1 if all else is well?

2023-08-24 11:08 UTC, merged